development:
  adapter: postgresql
  encoding: unicode
  database: perfci_development
  pool: 5
  username: perfci
  password:
test:
  adapter: postgresql
  encoding: unicode
  database: perfci_test
  pool: 5
  username: perfci
  password:
production:
  adapter: postgresql
  encoding: unicode
  database: perfci_production
  pool: 5
  username: perfci
  password:
