development:
  adapter: <%= ENV['DB_ADAPTER'] || 'postgresql' %>
  encoding: unicode
  host: <%= ENV['DB_HOST'] || 'localhost' %>
  database: <%= ENV['DB_NAME'] || 'perfci_development' %>
  pool: 5
  username: <%= ENV['DB_USER'] || 'perfci' %>
  password: <%= ENV['DB_PASS'] || '' %>
test:
  adapter: <%= ENV['DB_ADAPTER'] || 'postgresql' %>
  encoding: unicode
  host: <%= ENV['DB_HOST'] || 'localhost' %>
  database: <%= ENV['DB_NAME'] || 'perfci_test' %>
  pool: 5
  username: <%= ENV['DB_USER'] || 'perfci' %>
  password: <%= ENV['DB_PASS'] || '' %>
production:
  adapter: <%= ENV['DB_ADAPTER'] || 'postgresql' %>
  encoding: unicode
  host: <%= ENV['DB_HOST'] || 'localhost' %>
  database: <%= ENV['DB_NAME'] || 'perfci_production' %>
  pool: 5
  username: <%= ENV['DB_USER'] || 'perfci' %>
  password: <%= ENV['DB_PASS'] || '' %>
